### ISSUE TITLE
Prevent terminal type negotiation

### ISSUE THREAD

**Issue by flip111** [jquast/telnetlib3#31]
How can i disable the server wanting to negotiate terminal type with the client? I saw [this line of code](https://github.com/jquast/telnetlib3/blob/e063ec277521dd2379f042bc0b70896c5e6ef11f/telnetlib3/server.py#L90) but i'm not sure where begin_negotiation is called. At the moment i see the server sending `FF FD 18 IAC DO TERMINAL-TYPE` and the client responding `FF FC 18 IAC WON'T TERMINAL-TYPE`. Since i always connect to the same client i don't need this functionality.

**Comment by quixadhal** [comment]
Maybe fix your client to actually understand the TELNET protocol… or at least ignore opcodes that aren’t implemented?
Alternately, don’t use something called telnetlib if you don’t want to implement TELNET.  Just use a raw TCP socket and pretend none of this exists.

Sent from Mail for Windows 10

From: flip111
Sent: Friday, January 12, 2018 3:49
To: jquast/telnetlib3
Cc: Subscribed
Subject: [jquast/telnetlib3] Prevent terminal type negotiation (#31)

How can i disable the server wanting to negotiate terminal type with the client? I saw this line of code but i'm not sure where begin_negotiation is called. At the moment i see the server sending FF FD 18 IAC DO TERMINAL-TYPE and the client responding FF FC 18 IAC WON'T TERMINAL-TYPE. Since i always connect to the same client i don't need this functionality.

**Comment by flip111** [comment]
> Maybe fix your client to actually understand the TELNET protocol… or at least ignore opcodes that aren’t implemented?

How is the client not doing this by sending back `FF FC 18 IAC WON'T TERMINAL-TYPE` seems to me this code is also part of telnet.

**Comment by quixadhal** [comment]
You can’t expect to control the server’s behavior.  TELNET is asynchronous, in that either side can initiate a negotiation.  If you replied with the “I won’t do this”, you have effectively disabled it already, since the server won’t ask about it again unless YOU send a DO to ask it to do so.

It’s 100% standard behavior for a server to do general queries about the client’s capabilities when a connection is established.  So, again, if you want to use TELNET, you should expect (and respond to) any negotiations that come along, even if you don’t care about them.  Since most TELNET servers handle presentation layer stuff on the server side, it’s pretty normal to want to know things like how big your terminal is (NAWS) and what type of control codes it can deal with (TTYPE).

But hey, if you want to spend the time to make your own local modifications to rip out this functionality and ensure no other client that ever connects will ever work properly because a few extra bytes bothers you… go right ahead!  That’s why open source projects exist, so you can make your own changes.

Sent from Mail for Windows 10

**Comment by flip111** [comment]
> You can’t expect to control the server’s behavior.

Of course i expect to be able to control this. The server is telnetlib3. If things are not configurable it's a design decision of course. But i can't allow libraries to go out of out control if that's what you mean.

> you should expect (and respond to) any negotiations that come along

These negotiations don't just "come along", it is telnetlib3 that is generating the `FF FD 18` code. Meaning there is a specific thing in this code based which is generating it. Depending on the python code it will be easy or hard to change. Do you know where this code is? I looked for it but couldn't find the call site of `begin_negotiation`. If we know which is the code only then will we know what kind of modifications could be done.

> But hey, if you want to spend the time to make your own local modifications to rip out this functionality

No i don't want to "rip out functionality". I'm asking if it can be DISABLED. And i gauged there was a fair chance this was possible because the repository owner is doing some modification of IAC codes [in this ticket](https://github.com/jquast/telnetlib3/issues/24#issuecomment-203467324) ... but that was before the large refactor of the code.

> and ensure no other client that ever connects will ever work properly

I don't care about this, i always connect to the same client.

**Comment by jquast** [comment]
In DESIGN.rst is some notes under heading "wait_for", this was an advanced design that I did not make time for in 2015 when I first authored it, or 2017 when I refactored it, but I would be happy to accept any PR that produces the, "Await until specific negotation" behavior, in your case, negotate DONT TTYPE as quickly as possible.

The reason the server does ttype is because it seems to be the most basic thing to get some clients to kick their negotiation engines into spitting out their DO/WILL/WONT/whatevers, *something* has to be sent to get the gears running? anyway that's my memory of it, feel free to suggest code

**Comment by jquast** [comment]
suggest this pseudo-code:
```python
class MuteTelnetServer(telnetlib3.TelnetServer):
    def begin_negotiation(self):
        super().begin_negotiation()
```

where the IAC DO TTYPE is omitted, but like I said, this could cause some clients to stall or delay

https://github.com/jquast/telnetlib3/blob/b156c60c165295eb4d1a04824363f470d06e23ba/telnetlib3/server.py#L91
